--제약조건

--PRIMARY KEY (테이블의 고유 키, 중복X, NULL 허용 X)
--UNIQUE KEY (중복 X)
--NOT NULL (NULL 허용 X)
--FOREIGN KEY (참조하는 테이블의 PK를 저장하는 컬럼, 참조테이블의 PK가 없다면 등록X, NULL 허용)
--CHECK (정의된 형식만 저장되도록 허용)

DROP TABLE DEPT2;

CREATE TABLE DEPT2 ( --열 레벨 제약조건
    DEPT_NO NUMBER(2)       CONSTRAINT DEPT2_DEPT_NO_PK PRIMARY KEY,
    DEPT_NAME VARCHAR2(15)  NOT NULL,
    LOCA NUMBER(4)          CONSTRAINT DEPT2_LOCA_LOCID_FK
                            REFERENCES LOCATIONS(LOCATION_ID),
    DEPT_DATE DATE          DEFAULT SYSDATE, --아무것도 입력하지 않으면 자동으로 DEFAULT값이 저장
    DEPT_BONUS NUMBER(10),
    DEPT_PHONE VARCHAR2(20) NOT NULL CONSTRAINT DEPT2_DEPT_PHONE_UK UNIQUE,
    DEPT_GENDER CHAR(1)     CONSTRAINT DEPT2_DEPT_GENDER_CK 
                            CHECK(DEPT_GENDER IN ('M','F'))
);

CREATE TABLE DEPT2 ( --열 레벨 제약조건 (열 레벨에서는 CONSTRAINT구문 생략 가능)
    DEPT_NO NUMBER(2)       PRIMARY KEY,
    DEPT_NAME VARCHAR2(15)  NOT NULL,
    LOCA NUMBER(4)          REFERENCES LOCATIONS(LOCATION_ID),
    DEPT_DATE DATE          DEFAULT SYSDATE, --아무것도 입력하지 않으면 자동으로 DEFAULT값이 저장
    DEPT_BONUS NUMBER(10),
    DEPT_PHONE VARCHAR2(20) NOT NULL UNIQUE,
    DEPT_GENDER CHAR(1)     CHECK(DEPT_GENDER IN ('M','F'))
);


--테이블 레벨 제약조건

CREATE TABLE DEPT2 (
    DEPT_NO NUMBER(2),
    DEPT_NAME VARCHAR2(15) NOT NULL,
    LOCA NUMBER(4),
    DEPT_DATE DATE,
    DEPT_BONUS NUMBER(10),
    DEPT_PHONE VARCHAR2(20) NOT NULL,
    DEPT_GENDER CHAR(1),
    --테이블 레벨 제약조건은 아래쪽에 재약조건만 분리해서 작성 (슈퍼키 가능)
    CONSTRAINT DEPT2_DEPT_NO_PK PRIMARY KEY (DEPT_NO ,DEPT_NAME),
    CONSTRAINT DEPT2_DEPT_LOCA_LOCID_FK FOREIGN KEY (LOCA)
    REFERENCES LOCATIONS (LOCATION_ID),
    CONSTRAINT DEPT2_DEPT_PHONE_UK UNIQUE (DEPT_PHONE),
    CONSTRAINT DEPT2_DEPT_GENDER_CK CHECK(DEPT_GENDER IN ('M', 'F'))
);

DESC DEPT2;